site_name: ckanext-event-audit
site_url: https://.github.io/ckanext-event-audit/

repo_url:  https://github.com/DataShades/ckanext-event-audit

markdown_extensions:
  - pymdownx.details
  - pymdownx.snippets # include code snippets
  - pymdownx.highlight # code highlighting
  - pymdownx.inlinehilite # inline code highlighting
  - pymdownx.blocks.admonition # alert boxes
  - pymdownx.blocks.details # accordions
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: ["ckanext"]
          options:
            show_root_full_path: false
            show_root_toc_entry: false
            show_symbol_type_heading: true
            show_source: false
            docstring_section_style: spacy
  - search:
      separator: '[\s\-\.\_]+'

watch:
  - README.md
  - ckanext/event_audit/interfaces.py
  - ckanext/event_audit/exporters
  - ckanext/event_audit/repositories
  - ckanext/event_audit/utils.py
  - ckanext/event_audit/logic/validators.py
  - ckanext/event_audit/cli.py

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.select
    - content.code.annotate

nav:
  - index.md
  - install.md
  - usage.md
  - interfaces.md
  - validators.md
  - utils.md
  - cli.md

  - Configuration:
    - configure/active_repo.md
    - configure/cloudwatch.md
    - configure/ignore.md
    - configure/tracking.md
    - configure/async.md

  - Exporters:
    - exporters/basic.md
    - exporters/csv.md
    - exporters/tsv.md
    - exporters/json.md
    - exporters/xlsx.md

  - Repositories:
    - repositories/basic.md
    - repositories/abstract.md
    - repositories/redis.md
    - repositories/postgres.md
    - repositories/cloudwatch.md
    - repositories/custom.md
