version: 1
groups:
  - annotation: ckanext-event-audit
    options:
      - key: ckanext.event_audit.active_repo
        description: The active repository to store the audit logs
        default: redis
        validators: audit_repo_exists
        editable: true

      - key: ckanext.event_audit.restrict_available_repos
        description: The available repositories to store the audit logs
        type: list
        editable: false

      - key: ckanext.event_audit.cloudwatch.access_key
        description: The access key for the AWS account
        default: ''
        editable: true

      - key: ckanext.event_audit.cloudwatch.secret_key
        description: The secret key for the AWS account
        default: ''
        editable: true

      - key: ckanext.event_audit.cloudwatch.region
        description: The region for the AWS account
        default: ''
        editable: true

      - key: ckanext.event_audit.ignore.categories
        description: |
          A list of categories to exclude from event logging, applicable only to
          built-in tracking methods (API, database).
        type: list
        example: api view
        editable: true
        default: ''

      - key: ckanext.event_audit.ignore.actions
        description: |
          A list of actions to exclude from event logging, applicable only to
          built-in tracking methods (API, database).
        type: list
        example: package_create
        editable: true
        default: editable_config_list editable_config_change get_site_user ckanext_pages_list user_show

      - key: ckanext.event_audit.ignore.models
        description: |
          A list of models to exclude from event logging, applicable only to
          built-in tracking methods (API, database).
        type: list
        example: User Package Resource
        editable: true
        default: Option

      - key: ckanext.event_audit.track.model
        description: Enable logging of database events
        default: true
        editable: true
        type: bool

      - key: ckanext.event_audit.track.api
        description: Enable logging of API events
        default: true
        editable: true
        type: bool

      - key: ckanext.event_audit.store_payload_and_result
        description: Store the payload and result of the event
        default: false
        editable: true
        type: bool

      - key: ckanext.event_audit.batch.size
        description: The number of events to batch before sending to the repository
        default: 50
        editable: true
        type: int

      - key: ckanext.event_audit.batch.timeout
        description: Force push the events to the repository after this time in seconds since the last push
        default: 3600
        editable: true
        type: int

      - key: ckanext.event_audit.threaded_mode
        description: Enable threaded mode for pushing events to the repository
        default: true
        editable: false
        type: bool

      - key: ckanext.event_audit.enable_admin_panel
        description: Enable the admin panel
        default: true
        editable: false
        type: bool
