version: 1
groups:
  - annotation: ckanext-event-audit
    options:
      - key: ckanext.event_audit.active_repo
        description: The active repository to store the audit logs
        default: redis
        validators: audit_active_repo_validator
        editable: true

      - key: ckanext.event_audit.cloudwatch.access_key
        description: The access key for the AWS account
        default: ''
        editable: true

      - key: ckanext.event_audit.cloudwatch.secret_key
        description: The secret key for the AWS account
        default: ''
        editable: true

      - key: ckanext.event_audit.cloudwatch.region
        description: The region for the AWS account
        default: ''
        editable: true
